services:
  newtarr:
    image: ghcr.io/elfhosted/newtarr:v1.0.0
    container_name: newtarr
    environment:
      - TZ=${TZ}
    volumes:
      - ${APPDATA_DIR}/newtarr:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.newtarr.rule=Host(`newtarr.${DOMAIN_NAME}`)
      - traefik.http.routers.newtarr.entrypoints=websecure
      - traefik.http.routers.newtarr.tls.certresolver=letsencrypt
      - traefik.http.routers.newtarr.middlewares=security-headers@file
      - traefik.http.services.newtarr.loadbalancer.server.port=9705
    healthcheck:
      test: python3 -c "import http.client; conn = http.client.HTTPConnection('localhost', 9705); conn.request('GET', '/'); exit(0) if conn.getresponse().status == 200 else exit(1)" || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
