services:
  profilarr:
    image: santiagosayshey/profilarr:v1.1.4
    container_name: profilarr
    volumes:
      - ${APPDATA_DIR}/profilarr:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.http.routers.profilarr.rule=Host(`profilarr.${DOMAIN_NAME}`)
      - traefik.http.routers.profilarr.entrypoints=websecure
      - traefik.http.routers.profilarr.tls.certresolver=letsencrypt
      - traefik.http.routers.profilarr.middlewares=security-headers@file
      - traefik.http.services.profilarr.loadbalancer.server.port=6868
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:6868/ || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
