services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.0
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_DIR}/prowlarr:/config
      - /mnt:/mnt:rshared
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN_NAME}`)
      - traefik.http.routers.prowlarr.entrypoints=websecure
      - traefik.http.routers.prowlarr.tls.certresolver=letsencrypt
      - traefik.http.routers.prowlarr.middlewares=security-headers@file
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
    healthcheck:
      test: curl -f http://localhost:9696/ping || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
