services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:1.5.6
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_DIR}/bazarr:/config
      - /mnt:/mnt:rshared
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN_NAME}`)
      - traefik.http.routers.bazarr.entrypoints=websecure
      - traefik.http.routers.bazarr.tls.certresolver=letsencrypt
      - traefik.http.routers.bazarr.middlewares=security-headers@file
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
    healthcheck:
      test: curl -f http://localhost:6767 || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
