services:
  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    healthcheck:
      test: curl -f http://localhost:8191/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
