services:
  sonarr_anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr_anime
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_DIR}/sonarr_anime:/config
      - /mnt:/mnt:rshared
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr-anime.rule=Host(`sonarr-anime.${DOMAIN_NAME}`)
      - traefik.http.routers.sonarr-anime.entrypoints=websecure
      - traefik.http.routers.sonarr-anime.tls.certresolver=letsencrypt
      - traefik.http.routers.sonarr-anime.middlewares=security-headers@file
      - traefik.http.services.sonarr-anime.loadbalancer.server.port=8989
    healthcheck:
      test: curl -f http://localhost:8989/ping || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
