services:
  decypharr:
    image: ghcr.io/sirrobot01/decypharr:v1.1.6
    container_name: decypharr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /mnt/media:/mnt:rshared
      - ${APPDATA_DIR}/decypharr:/app
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    labels:
      - traefik.enable=true
      - traefik.http.routers.decypharr.rule=Host(`decypharr.${DOMAIN_NAME}`)
      - traefik.http.routers.decypharr.entrypoints=websecure
      - traefik.http.routers.decypharr.tls.certresolver=letsencrypt
      - traefik.http.routers.decypharr.middlewares=security-headers@file
      - traefik.http.services.decypharr.loadbalancer.server.port=8282
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck", "--config", "/app/"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
