services:
  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: unless-stopped
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    volumes:
      - ${APPDATA_DIR}/redis:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - traefik

  redis_exporter:
    image: oliver006/redis_exporter:v1.66.0
    container_name: redis_exporter
    restart: unless-stopped
    environment:
      REDIS_ADDR: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - traefik

networks:
  traefik:
    external: true
